### ISSUE TITLE
Torch LR autoencoder and vae not working

### ISSUE THREAD

**Issue by jreps** [OHDSI/PatientLevelPrediction#107]
When I tried to run the LR using the Torch backend and set autoencoder to T or vae to T I get this error:
Error in value[[3L]](cond) : 
  Error in pyExecp(sprintf("execfile('%s')", as.character(filename)[1])): 
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
     File "<string>", line 2, in execfile
     File "C:/Users/jreps/Documents/R/win-library/3.5/PatientLevelPrediction/python/deepTorch.py", line 862, in <module>
       auto_model = VAE(input_size=train_x.shape[1], encoding_size=encoding_size)
     File "C:/Users/jreps/Documents/R/win-library/3.5/PatientLevelPrediction/python/deepTorch.py", line 181, in __init__
       self.fc1 = nn.Linear(input_size, input_size/2)
     File "C:\Users\jreps\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\modules\linear.py", line 41, in __init__
       self.weight = Parameter(torch.Tensor(out_features, in_features))
   TypeError: new() received an invalid combination of arguments - got (float, int), but expected one of:
    * (torch.device device)
    * (torch.Storage storage)
    * (Tensor other)
    * (tuple of ints size, torch

It seems an input error in the VAE and AutoEncoder functions?

**Comment by xypan1232** [comment]
Could I ask what is the python and pytorch version?

**Comment by jreps** [comment]
pytorch: 0.4.1
python: 3.6.4

**Comment by xypan1232** [comment]
I ran the testing on Ubuntu and python 2.7, it does not report errors. Maybe i need test it on windows to see.
